spring.application.name=esientradas

# BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/esientradas?serverTimezone=UTC&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&maxAllowedPacket=134217728
spring.datasource.username=root
spring.datasource.password=1234

# Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ddl auto (update crea/modifica tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update

server.error.include-message=always

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Clave SECRETA — solo se usa en el backend (PagosService)

# Clave PÚBLICA — exponerla al frontend si es necesario
